version: '3'
services:
  blog-article:
    container_name: blog-article
    build:
      context: ./blog-article
      dockerfile: Dockerfile
    ports:
      - "10000:10000"

  blog-gateway:
    container_name: blog-gateway
    build: # 服务的 Docker 构建文件位置
      context: ./blog-gateway
      dockerfile: Dockerfile
    ports:
      - "88:88"

  blog-message:
    container_name: blog-message
    build:
      context: ./blog-message
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  blog-picture:
    container_name: blog-picture
    build:
      context: ./blog-picture
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

  blog-search:
    container_name: blog-search
    build:
      context: ./blog-search
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  blog-user:
    container_name: blog-user
    build:
      context: ./blog-user
      dockerfile: Dockerfile
    ports:
      - "6000:6000"