version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./doc/sql:/docker-entrypoint-initdb.d
    restart: always
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
    restart: always
  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
    restart: always
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    restart: always
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/Shanghai
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es
      cluster.name: elasticsearch
      discovery.type: single-node
    volumes:
      - ./.elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g