# Tomcat
server:
  port: 6000
  servlet:
    context-path: /user
# 注册中心 配置中心
spring:
  application:
    name: blog-user
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  config:
    import: application.yml
  #      config:
  #        # 配置中心地址
  #        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: 123456
    virtual-host: /