# Tomcat
server:
  port: 9000
  servlet:
    context-path: /message
# 注册中心 配置中心
spring:
  application:
    name: blog-message
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 116.62.87.229:8848
      config:
        import-check:
          enabled: false
  
  rabbitmq:
    host: 116.62.87.229
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.87.229:3306/blog
    username: root
    password: kai@zhang0016
  redis:
    host: 116.62.87.229
    port: 6379
#      config:
#        # 配置中心地址
#        server-addr: 116.62.87.229:8848