# Tomcat
server:
  port: 88
# 注册中心 配置中心
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
#      config:
#        # 配置中心地址
#        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: web_route
          uri: lb://blog-web-backend
          predicates:
            - Path=/api/web/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
  config:
    import: application.yml