# Tomcat
server:
  port: 88
# 注册中心 配置中心
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: localhost:8848
#      config:
#        # 配置中心地址
#        server-addr: localhost:8848

    gateway:
      routes:
        # 文章服务
        - id: article_route
          uri: lb://blog-article
          predicates:
            - Path=/api/article/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 图片服务
        - id: picture_route
          uri: lb://blog-picture
          predicates:
            - Path=/api/picture/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 检索服务
        - id: search_route
          uri: lb://blog-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 消息服务
        - id: message_route
          uri: lb://blog-message
          predicates:
            - Path=/api/message/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 用户服务
        - id: user_route
          uri: lb://blog-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

auth:
  # 不需要登录 即可访问的地址
  excludePaths:
    - /api/picture/**
    - /api/user/getAuthUser
    - /api/user/getUserInfo
    - /api/article/category/**
    - /api/article/preview/**
    - /api/message/websocket/**
    - /api/search/**
