# Tomcat
server:
  port: 8000
#  servlet:
#    context-path: /search
# 注册中心 配置中心
spring:
  application:
    name: blog-search
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 116.62.87.229:8848
      config:
        import-check:
          enabled: false

  elasticsearch:
    uris: localhost:9200
#      config:
#        # 配置中心地址
#        server-addr: 116.62.87.229:8848
