# Tomcat
server:
  port: 10000
  servlet:
    context-path: /web
# 注册中心 配置中心
spring:
  application:
    name: blog-web-backend
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  config:
    import: application.yml
#      config:
#        # 配置中心地址
#        server-addr: 127.0.0.1:8848
# 其他配置均在nacos